-- 创建数据库（适配SQL Server 2022）
CREATE DATABASE ERP_WMS_TMS_DB
ON PRIMARY (
    NAME = 'ERP_WMS_TMS_DB',
    FILENAME = 'C:\SQLData\ERP_WMS_TMS_DB.mdf',  -- 路径可根据Win11实际环境修改
    SIZE = 1024MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 256MB
)
LOG ON (
    NAME = 'ERP_WMS_TMS_DB_Log',
    FILENAME = 'C:\SQLData\ERP_WMS_TMS_DB.ldf',
    SIZE = 512MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 128MB
);
GO

-- 使用数据库
USE ERP_WMS_TMS_DB;
GO

-- 设置数据库排序规则（支持中文）
ALTER DATABASE ERP_WMS_TMS_DB 
COLLATE Chinese_PRC_CI_AS;
GO